# Generated by Django 3.1.1 on 2020-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPT', models.DecimalField(decimal_places=2, max_digits=5)),
                ('samplingDepth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classification', models.CharField(max_length=20)),
                ('groupSymbol', models.CharField(max_length=3)),
                ('layer', models.CharField(max_length=20)),
                ('gamma', models.DecimalField(decimal_places=4, max_digits=10)),
                ('waterPercentage', models.DecimalField(decimal_places=4, max_digits=6)),
                ('cValue', models.FloatField()),
                ('phiValue', models.FloatField()),
                ('GI', models.CharField(max_length=3)),
            ],
        ),
    ]
