# Generated by Django 3.1.1 on 2020-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Elasticity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Nvalue',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='data',
            name='nu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='SPT',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='cValue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='classification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='gamma',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='groupSymbol',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='phiValue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='thickness',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='waterPercentage',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
