# Generated by Django 3.1.1 on 2020-09-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20200928_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Nvalue',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
