# Generated by Django 3.1.1 on 2020-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPT', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Nvalue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('samplingDepth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('classification', models.CharField(max_length=20, null=True)),
                ('groupSymbol', models.CharField(max_length=3, null=True)),
                ('layer', models.CharField(max_length=20, null=True)),
                ('gamma', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('waterPercentage', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('cValue', models.FloatField(null=True)),
                ('phiValue', models.FloatField(null=True)),
                ('GI', models.CharField(max_length=3)),
                ('Elasticity', models.FloatField(null=True)),
                ('nu', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='excelUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelFile', models.FileField(upload_to='excelFile/files/')),
            ],
        ),
    ]
